Repository momogum/momogum_BE, pull requests merged in 2025-02, with the labels that each got.

#52 [Feat/#30] 유저 프로필 기능
  MERGE_MSG
  src/main/java/com/example/momogum/apiPayLoad/exception/handler/FollowCategoryHandler.java
  src/main/java/com/example/momogum/converter/followConverter/FollowConverter.java
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryCommentConverter.java
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryConverter.java
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryLikeConverter.java
  src/main/java/com/example/momogum/domain/Follower.java
  src/main/java/com/example/momogum/domain/Following.java
  src/main/java/com/example/momogum/domain/ProfileImage.java
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/domain/UserProfileImage.java
  src/main/java/com/example/momogum/repository/ProfileImageRepo/ProfileImageRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowerRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowingRepository.java
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/service/userProfileService/FollowService.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/ProfileImageService.java
  src/main/java/com/example/momogum/service/userProfileService/ProfileImageServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileService.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryServiceImpl.java
  src/main/java/com/example/momogum/util/ImageUtil.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
  src/main/java/com/example/momogum/web/dto/FollowDTO.java
  src/main/java/com/example/momogum/web/dto/UserDTO.java
  src/main/java/com/example/momogum/web/dto/user/ProfileImageDTO.java
  src/main/java/com/example/momogum/web/dto/user/UserDTO.java
Labels: :sparkles: feat

#56 [FEATURE] 검색 기능 구현 #50
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/apiPayLoad/exception/handler/SearchHandler.java
  src/main/java/com/example/momogum/config/RedisConfig.java
  src/main/java/com/example/momogum/converter/searchConverter/SearchConverter.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/service/searchService/SearchService.java
  src/main/java/com/example/momogum/service/searchService/SearchServiceImpl.java
  src/main/java/com/example/momogum/web/controller/search/SearchController.java
  src/main/java/com/example/momogum/web/dto/search/SearchDTO.java
Labels: :sparkles: feat

#59 feat: 조회 기능 설계 #57
  src/main/java/com/example/momogum/converter/userConverter/UserProfileConverter.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileService.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
  src/main/java/com/example/momogum/web/dto/user/UserDTO.java
Labels: :sparkles: feat

#55 [Feat/#34] 카카오 로그인 및 레디스 JWT 토큰관리
  build.gradle
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/apiPayLoad/exception/DuplicateUserException.java
  src/main/java/com/example/momogum/apiPayLoad/exception/ExceptionAdvice.java
  src/main/java/com/example/momogum/config/RedisConfig.java
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/domain/utils/JwtUtil.java
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/service/TokenService.java
  src/main/java/com/example/momogum/service/UserService.java
  src/main/java/com/example/momogum/web/controller/AuthController.java
  src/main/java/com/example/momogum/web/dto/AuthDTO.java
  src/main/java/com/example/momogum/web/dto/user/KakaoResponseDTO.java
  src/main/java/com/example/momogum/web/dto/user/UserDTO.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#62 [Feat/#60] 약속 잡기 친구초대 로직 구현
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentInviteConverter.java
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentNameConverter.java
  src/main/java/com/example/momogum/domain/Following.java
  src/main/java/com/example/momogum/domain/appointment/AppointmentInvitation.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentInvitationRepository.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentInviteRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowingRepository.java
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentCardService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentInviteService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentNameService.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentCardsController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentInviteController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentNameController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointMentDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentCardDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentInviteDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentNameDTO.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentCardServiceTest.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentInviteServiceTest.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentNameServiceTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentCardsControllerTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentNameControllerTest.java
Labels: :sparkles: feat

#63 [Feat/#61] 유저 프로필 로직 구현
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/converter/followConverter/FollowConverter.java
  src/main/java/com/example/momogum/domain/Following.java
  src/main/java/com/example/momogum/repository/ProfileImageRepo/ProfileImageRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowerRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowingRepository.java
  src/main/java/com/example/momogum/service/userProfileService/FollowService.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/ProfileImageServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileService.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/validation/validator/UserProfileValidator.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/FollowController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
  src/main/java/com/example/momogum/web/dto/FollowDTO.java
Labels: :sparkles: feat

#65 [feat] 스토리 기능 구현
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/apiPayLoad/exception/handler/MealDiaryStoryHandler.java
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryStoryConverter.java
  src/main/java/com/example/momogum/domain/MealDiary.java
  src/main/java/com/example/momogum/domain/MealDiaryStory.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryStoryRepository.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryServiceImpl.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryService.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/mealDiary/MealStoryController.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDiaryStoryReadDTO.java
  src/test/java/com/example/momogum/repository/followRepo/FollowingRepositoryTest.java
  src/test/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepositoryTest.java
  src/test/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryStoryRepositoryTest.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentCardServiceTest.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImplTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentCardsControllerTest.java
Labels: :sparkles: feat

#66 [chore] 테스트 통과 구현
  src/test/java/com/example/momogum/service/appointmentService/AppointmentCardServiceTest.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentInviteServiceTest.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentNameServiceTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentCardsControllerTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentNameControllerTest.java
Labels: :pencil2: chore

#70 [chore] 기존 팔로우 테이블에 맞게 약속 잡기 친구 초대 부분 수정 및 맞팔로우 테이블 반환 + 테스트 코드 통과
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentInviteService.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentInviteServiceTest.java
Labels: :pencil2: chore

#72 [FEATURE] 메인 페이지 조회 로직 2차 #54
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/converter/searchConverter/SearchConverter.java
  src/main/java/com/example/momogum/repository/followRepo/FollowerRepository.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/repository/redisRepository/RedisRepository.java
  src/main/java/com/example/momogum/service/searchService/SearchService.java
  src/main/java/com/example/momogum/service/searchService/SearchServiceImpl.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/search/SearchController.java
  src/main/java/com/example/momogum/web/dto/search/FollowStatusDTO.java
  src/main/java/com/example/momogum/web/dto/search/SearchDTO.java
Labels: :chains: refactor, :sparkles: feat

#73 [Chore] 유저프로필 로직 수정
  src/main/java/com/example/momogum/converter/ViewMealDiaryConverter.java
  src/main/java/com/example/momogum/converter/userConverter/UserProfileConverter.java
  src/main/java/com/example/momogum/domain/UserProfileImage.java
  src/main/java/com/example/momogum/repository/ProfileImageRepo/ProfileImageRepository.java
  src/main/java/com/example/momogum/repository/profileImageRepo/ProfileImageRepository.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileService.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/FollowController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/TargetProfileController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
  src/main/java/com/example/momogum/web/dto/user/UserDTO.java
Labels: :pencil2: chore

#78 [fix] 배포 환경 프로필 이미지 엔티티 created_at, updated_at null 에러 수정
  src/main/java/com/example/momogum/domain/ProfileImage.java
  src/main/java/com/example/momogum/service/TokenService.java
Labels: :wrench: fix

#79 [FEAT] 프로필 이미지 업로드 메서드
  src/main/java/com/example/momogum/domain/ProfileImage.java
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/domain/UserProfileImage.java
  src/main/java/com/example/momogum/repository/profileImageRepo/ProfileImageRepository.java
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/service/userProfileService/ProfileImageService.java
  src/main/java/com/example/momogum/service/userProfileService/ProfileImageServiceImpl.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
Labels: :sparkles: feat

#82 [FEAT] 상대 프로필 API
  src/main/java/com/example/momogum/converter/followConverter/TargetFollowConverter.java
  src/main/java/com/example/momogum/converter/userConverter/TargetProfileConverter.java
  src/main/java/com/example/momogum/converter/userConverter/UserReportConverter.java
  src/main/java/com/example/momogum/repository/followRepo/FollowerRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowingRepository.java
  src/main/java/com/example/momogum/repository/profileImageRepo/ProfileImageRepository.java
  src/main/java/com/example/momogum/service/userProfileService/FollowService.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/TargetProfileService.java
  src/main/java/com/example/momogum/service/userProfileService/TargetProfileServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/FollowController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/TargetProfileController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
  src/main/java/com/example/momogum/web/dto/FollowDTO.java
  src/main/java/com/example/momogum/web/dto/TargetDTO.java
  src/main/java/com/example/momogum/web/dto/search/SearchDTO.java
  src/main/java/com/example/momogum/web/dto/user/TargetProfileDTO.java
  src/main/java/com/example/momogum/web/dto/user/UserDTO.java
  src/main/java/com/example/momogum/web/dto/user/UserReportDTO.java
Labels: :sparkles: feat

#84 [Feat/#80] S3이미지로 약속잡기 카드 부분 수정
  src/main/java/com/example/momogum/domain/common/enums/CardCategory.java
  src/main/java/com/example/momogum/domain/utils/S3UrlProvider.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentCardService.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentCardsController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentCardDTO.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentCardServiceTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentCardsControllerTest.java
Labels: :pencil2: chore

#85 [chore] 프론트 요구사항에 따른 기능 수정
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryStoryConverter.java
  src/main/java/com/example/momogum/domain/MealDiaryStory.java
  src/main/java/com/example/momogum/domain/MealDiaryStoryView.java
  src/main/java/com/example/momogum/domain/common/BaseEntity.java
  src/main/java/com/example/momogum/domain/common/enums/FoodCategory.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryStoryRepository.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryStoryViewRepository.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryService.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
  src/main/java/com/example/momogum/util/LocalDateTImeHolderImpl.java
  src/main/java/com/example/momogum/util/LocalDateTimeHolder.java
  src/main/java/com/example/momogum/web/controller/mealDiary/MealStoryController.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDiaryStoryReadDTO.java
  src/test/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryStoryRepositoryTest.java
Labels: :pencil2: chore

#90 [chore] 스토리 전체조회 응답값에 스토리 식별자 추가
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryStoryConverter.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDiaryStoryReadDTO.java
Labels: :pencil2: chore

#91 [Feat#88] 약속잡기 전체 로직 구현 (Orchestrator 패턴 적용)
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentNameConverter.java
  src/main/java/com/example/momogum/domain/common/enums/CardCategory.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentNameService.java
  src/main/java/com/example/momogum/service/appointmentService/orchestrator/AppointmentOrchestrator.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentNameController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentOrchestratorController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentInviteDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentNameDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentOrchestratorDTO.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentNameServiceTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentNameControllerTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentOrchestratorTest.java
Labels: :sparkles: feat

#94 [fix] 테스트 수정 및 프론트 요구사항 반영
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryStoryConverter.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDiaryStoryReadDTO.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImplTest.java
Labels: :pencil2: chore, :test_tube: test

#97 [REFACTOR] 프로필 조회 API 수정
  src/main/java/com/example/momogum/domain/ProfileImage.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/FollowController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
Labels: :chains: refactor

#100 [chore] 스토리 응답값에 생성일자 포함하도록 수정
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryStoryConverter.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDiaryStoryReadDTO.java
Labels: :pencil2: chore

#105 [fix] 조회 엔티티 중복 저장 오류 해결
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
Labels: :wrench: fix

#96 [chore/#92] 오케스트레이션 패턴 수정 구현
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentConverter.java
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentInviteConverter.java
  src/main/java/com/example/momogum/domain/appointment/Appointment.java
  src/main/java/com/example/momogum/domain/appointment/AppointmentCard.java
  src/main/java/com/example/momogum/domain/appointment/AppointmentInvitation.java
  src/main/java/com/example/momogum/domain/utils/JwtUtil.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentCardRepository.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentRepository.java
  src/main/java/com/example/momogum/service/UserService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentCardService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentInviteService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentNameService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
  src/main/java/com/example/momogum/service/appointmentService/orchestrator/AppointmentOrchestrator.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentCardsController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentInitController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentInviteController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentNameController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentCardDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentOrchestratorDTO.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentInviteServiceTest.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentNameServiceTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentNameControllerTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentOrchestratorTest.java
Labels: :pencil2: chore

#107 [chore] 스토리 서비스 로직 리팩터링 및 테스트 코드 작성
  .DS_Store
  .gitignore
  src/.DS_Store
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryStoryConverter.java
  src/main/java/com/example/momogum/domain/MealDiaryStory.java
  src/main/java/com/example/momogum/domain/common/BaseEntity.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryServiceImpl.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImplTest.java
Labels: :chains: refactor, :pencil2: chore, :test_tube: test

#109 [FIX] 메인 페이지 조회 로직 오류 수정 #102 Open
  src/main/java/com/example/momogum/converter/ViewMealDiaryConverter.java
  src/main/java/com/example/momogum/domain/common/enums/FoodCategory.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryService.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/viewMealDiary/ViewMealDiaryController.java
  src/main/java/com/example/momogum/web/dto/viewMealDiary/ViewMealDiaryDTO.java
Labels: :chains: refactor, :pencil2: chore, :sparkles: feat, :wrench: fix

#112 [feat] 현재 로그인 된 유저 정보 확인, 회원탈퇴 API 추가
  src/main/java/com/example/momogum/service/TokenService.java
  src/main/java/com/example/momogum/service/UserService.java
  src/main/java/com/example/momogum/web/controller/AuthController.java
Labels: :sparkles: feat

#113 [Refactor] 서비스 메서드 분리
  src/main/java/com/example/momogum/converter/followConverter/FollowConverter.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/TargetProfileServiceImpl.java
  src/main/java/com/example/momogum/web/controller/AuthController.java
Labels: :chains: refactor

#115 [feat] 프론트 요구사항 반영
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryConverter.java
  src/main/java/com/example/momogum/domain/MealDiary.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryKeywordRepository.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryCommentServiceImpl.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryService.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/mealDiary/MealDiaryController.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDairiesDTO.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDiaryUpdateDTO.java
  src/test/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryKeywordRepositoryTest.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryServiceImplTest.java
Labels: :pencil2: chore, :sparkles: feat, :test_tube: test

#117 [FIX] 팔로잉 토글, 팔로워 삭제 토글 오류 수정
  .DS_Store
  src/main/java/com/example/momogum/converter/followConverter/TargetFollowConverter.java
  src/main/java/com/example/momogum/converter/userConverter/TargetProfileConverter.java
  src/main/java/com/example/momogum/repository/followRepo/FollowerRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowingRepository.java
  src/main/java/com/example/momogum/service/userProfileService/FollowService.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/ProfileImageServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/TargetProfileService.java
  src/main/java/com/example/momogum/service/userProfileService/TargetProfileServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/FollowController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/TargetProfileController.java
  src/main/java/com/example/momogum/web/dto/FollowDTO.java
Labels: :wrench: fix

#120 [chore] List 형태로 반환하기
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryService.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/mealDiary/MealStoryController.java
Labels: :pencil2: chore

#121 [FEAT] 프로필에서 밥일기 조회시 이미지 조회 추가했습니다.
  src/main/java/com/example/momogum/converter/ViewMealDiaryConverter.java
  src/main/java/com/example/momogum/service/userProfileService/UserProfileServiceImpl.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/TargetProfileController.java
Labels: :sparkles: feat

#122 [FIX] 밥일기 검색 에러 수정 #111
  src/main/java/com/example/momogum/converter/searchConverter/SearchConverter.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/service/searchService/SearchServiceImpl.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryService.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/viewMealDiary/ViewMealDiaryController.java
  src/main/java/com/example/momogum/web/dto/search/SearchDTO.java
Labels: :pencil2: chore, :sparkles: feat, :wrench: fix

#123 [Feat/#108] ID로 보낸 초대장 확인 및, 약속관리 메인페이지에서 PENDING/ACCEPTED 상태에 맞게 약속 조회 로직 구현
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentConverter.java
  src/main/java/com/example/momogum/domain/appointment/Appointment.java
  src/main/java/com/example/momogum/domain/appointment/AppointmentInvitation.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentInviteRepository.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentInviteService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
  src/main/java/com/example/momogum/service/appointmentService/orchestrator/AppointmentOrchestrator.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentDTO.java
  src/test/java/com/example/momogum/service/appointmentService/AppointmentInviteServiceTest.java
Labels: :sparkles: feat

#130 [feat] fcm 테스트 api 구현
  .DS_Store
  .github/workflows/dev_CD.yml
  build.gradle
  src/.DS_Store
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/fcm/FcmMessageRequestDto.java
  src/main/java/com/example/momogum/fcm/FirebaseCloudMessageService.java
  src/main/java/com/example/momogum/fcm/FirebaseController.java
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/service/TokenService.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/AuthController.java
  src/main/java/com/example/momogum/web/dto/AuthDTO.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImplTest.java
Labels: :sparkles: feat

#131 [fix] firebase 필드 생성
  .DS_Store
  .github/.DS_Store
  .gitignore
  src/.DS_Store
  src/main/resources/firebase/test
Labels: :wrench: fix

#132 [feat] FCM 로직 수정
  build.gradle
  src/main/java/com/example/momogum/fcm/FcmController.java
  src/main/java/com/example/momogum/fcm/FcmMessage.java
  src/main/java/com/example/momogum/fcm/FcmMessageRequestDto.java
  src/main/java/com/example/momogum/fcm/FirebaseCloudMessageService.java
  src/main/java/com/example/momogum/fcm/FirebaseController.java
  src/main/java/com/example/momogum/fcm/RequestDTO.java
Labels: :pencil2: chore

#133 [CHORE] targetProfile 엔드포인트 수정
  src/main/java/com/example/momogum/web/controller/UserProfileController/FollowController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/TargetProfileController.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
Labels: :pencil2: chore

#145 [CHORE] dto 프론트 요구사항수정 #143
  src/main/java/com/example/momogum/converter/searchConverter/SearchConverter.java
  src/main/java/com/example/momogum/web/dto/search/SearchDTO.java
Labels: :pencil2: chore

#147 accept, confirmed API 구현
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentConverter.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentInviteRepository.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentController.java
Labels: :pencil2: chore

#150 [chore] 요청사항 맞춰 ttl_minutes -> ttl_seconds 변경
  src/main/java/com/example/momogum/repository/redisRepository/RedisRepository.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryServiceImpl.java
Labels: :pencil2: chore

#151 [chore] init 문제 해결
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentInitControllerTest.java
Labels: :pencil2: chore

#158 [feat] 푸시 알림 기능 활용 & 밥일기 반환값 수정
  src/main/java/com/example/momogum/converter/mealDiaryConverter/MealDiaryConverter.java
  src/main/java/com/example/momogum/domain/MealDiary.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryCommentService.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryCommentServiceImpl.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryLikeService.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryLikeServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/FollowService.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
  src/main/java/com/example/momogum/util/FirebaseCloudMessageUtil.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/FollowController.java
  src/main/java/com/example/momogum/web/controller/mealDiary/MealDiaryCommentController.java
  src/main/java/com/example/momogum/web/controller/mealDiary/MealDiaryLikeController.java
  src/main/java/com/example/momogum/web/dto/mealDiary/MealDairiesDTO.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryCommentServiceImplTest.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryServiceImplTest.java
Labels: :pencil2: chore, :sparkles: feat, :test_tube: test

#159 [fix] 밥일기 영속성 전이 오류 해결
  src/main/java/com/example/momogum/domain/MealDiaryStory.java
Labels: :wrench: fix

#161 [fix] 프로필 이미지 로직 수정
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryServiceImpl.java
Labels: :wrench: fix

#163 [FIX] 회원 검색 결과 스토리 반환 오류 #162
  src/main/java/com/example/momogum/service/searchService/SearchServiceImpl.java
Labels: :wrench: fix

#165 [fix] 조회 여부 재수정
  src/main/java/com/example/momogum/service/searchService/SearchServiceImpl.java
Labels: :wrench: fix

#169 [feat] 푸시알림 로직 수정
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryCommentServiceImpl.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryLikeServiceImpl.java
  src/main/java/com/example/momogum/service/userProfileService/FollowServiceImpl.java
Labels: :pencil2: chore

#172 [fix] 테스트 코드 오류 수정
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/service/mealDiaryService/MealDiaryLikeServiceImpl.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryBookmarkServiceImplTest.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryCommentServiceImplTest.java
Labels: :test_tube: test, :wrench: fix

#173 [Fix/#171] accpeted, confirmed 반환값 수정
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentConverter.java
  src/main/java/com/example/momogum/domain/appointment/Appointment.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentInviteRepository.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentDTO.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentInitControllerTest.java
Labels: :pencil2: chore, :wrench: fix

#175 [Fix/#174] 약속잡기 whole 메서드 수정
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentConverter.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentCardService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentInviteService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
  src/main/java/com/example/momogum/service/appointmentService/orchestrator/AppointmentOrchestrator.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentInitController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentOrchestratorDTO.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentInitControllerTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentOrchestratorTest.java
Labels: :pencil2: chore, :wrench: fix

#177 [feat] 좋아요 기능 테스트 코드 추가
  src/main/java/com/example/momogum/domain/MealDiary.java
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryLikeServiceImplTest.java
Labels: :test_tube: test

#178 [Fix/#176] appointmentId 업데이트 수정 및 카드 한 개 반환
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentConverter.java
  src/main/java/com/example/momogum/domain/appointment/Appointment.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentCardService.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
  src/main/java/com/example/momogum/service/appointmentService/orchestrator/AppointmentOrchestrator.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentOrchestratorDTO.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentOrchestratorTest.java
Labels: :wrench: fix

#189 [feat] 스토리 조회 오류 해결
  src/test/java/com/example/momogum/service/mealDiaryService/MealDiaryStoryServiceImplTest.java
Labels: :sparkles: feat, :wrench: fix

#190 [Fix/#187] 14L, 12L 더미데이터 이용
  src/main/java/com/example/momogum/service/appointmentService/AppointmentInviteService.java
  src/main/java/com/example/momogum/service/appointmentService/orchestrator/AppointmentOrchestrator.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentInviteDTO.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointmentOrchestratorDTO.java
Labels: :wrench: fix

#192 [Fix/#187] update 수정
  src/main/java/com/example/momogum/domain/appointment/Appointment.java
  src/main/java/com/example/momogum/service/appointmentService/AppointmentService.java
Labels: :wrench: fix

#194 [Fix/#193] 친구 더미데이터 추가
  src/main/java/com/example/momogum/converter/appointmentConverter/AppointmentConverter.java
Labels: :wrench: fix
