Repository momogum/momogum_BE, pull requests merged in 2025-01, with the labels that each got.

#15 [feat] API 명세 예시 템플릿 작성
  src/main/java/com/example/momogum/web/controller/TestController.java
  src/main/java/com/example/momogum/web/dto/TestDTO.java
Labels: :page_facing_up: doc

#17 [feat] 스토리 & 하이라이트 API 명세서 작성
  src/main/java/com/example/momogum/web/controller/HighlightController.java
  src/main/java/com/example/momogum/web/controller/StoryController.java
  src/main/java/com/example/momogum/web/controller/TestController.java
  src/main/java/com/example/momogum/web/dto/HighlightDTO.java
  src/main/java/com/example/momogum/web/dto/StoryDTO.java
Labels: :page_facing_up: doc

#20 [feat] 약속잡기 API 명세서 작성
  src/main/java/com/example/momogum/domain/common/mealPlan/Proposal.java
  src/main/java/com/example/momogum/web/controller/mealPlan/MealPlanController.java
  src/main/java/com/example/momogum/web/dto/mealPlan/MealPlanDTO.java
  src/main/java/com/example/momogum/web/dto/user/UserDTO.java
Labels: :page_facing_up: doc

#24 [feat] 유저프로필 기술 명세서
  src/main/java/com/example/momogum/service/UserService.java
  src/main/java/com/example/momogum/web/controller/UserProfileController/UserProfileController.java
  src/main/java/com/example/momogum/web/dto/MealDiaryDTO.java
  src/main/java/com/example/momogum/web/dto/UserDTO.java
Labels: :page_facing_up: doc

#25 [feat] 유저 로그인 기술 명세서
  .DS_Store
  .github/.DS_Store
  build.gradle
  src/.DS_Store
  src/main/java/com/example/momogum/config/RedisConfig.java
  src/main/java/com/example/momogum/domain/FollowEntity.java
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/domain/UserPreferenceEntity.java
  src/main/java/com/example/momogum/service/TokenService.java
  src/main/java/com/example/momogum/web/controller/AuthController.java
  src/main/java/com/example/momogum/web/dto/AuthDTO.java
  src/main/resources/application.yml
Labels: :page_facing_up: doc

#27 [feat] 필요 엔티티 구현
  src/main/java/com/example/momogum/domain/AppointmentCard.java
  src/main/java/com/example/momogum/domain/AppointmentInvitation.java
  src/main/java/com/example/momogum/domain/AppointmentManager.java
  src/main/java/com/example/momogum/domain/FollowEntity.java
  src/main/java/com/example/momogum/domain/MealDiary.java
  src/main/java/com/example/momogum/domain/MealDiaryBookmark.java
  src/main/java/com/example/momogum/domain/MealDiaryComments.java
  src/main/java/com/example/momogum/domain/MealDiaryLikes.java
  src/main/java/com/example/momogum/domain/Photo.java
  src/main/java/com/example/momogum/domain/Report.java
  src/main/java/com/example/momogum/domain/TestEntity.java
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/domain/UserPreferenceEntity.java
  src/main/java/com/example/momogum/domain/common/enums/FoodCategory.java
  src/main/java/com/example/momogum/domain/common/enums/InvitationStatus.java
  src/main/java/com/example/momogum/domain/common/enums/IsRevisit.java
  src/main/java/com/example/momogum/domain/common/enums/KeyWord.java
  src/main/java/com/example/momogum/domain/common/enums/LoginType.java
  src/main/java/com/example/momogum/domain/common/enums/Proposal.java
  src/main/java/com/example/momogum/repository/appointmentCardRepo/AppointmentCardRepository.java
  src/main/java/com/example/momogum/repository/appointmentInvitationRepo/AppointmentInvitationRepository.java
  src/main/java/com/example/momogum/repository/appointmentManagerRepo/AppointmentManagerRepository.java
  src/main/java/com/example/momogum/repository/followRepo/FollowRepository.java
  src/main/java/com/example/momogum/repository/mealDiaryBookmarkRepo/MealDiaryBookmarkRepository.java
  src/main/java/com/example/momogum/repository/mealDiaryCommentsRepo/MealDiaryCommentsRepository.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/repository/photoRepo/PhotoRepository.java
  src/main/java/com/example/momogum/repository/reportRepo/ReportRepository.java
  src/main/java/com/example/momogum/repository/userEntityRepo/UserEntityRepository.java
  src/main/java/com/example/momogum/repository/userPreferenceRepo/UserPreferenceRepository.java
  src/main/java/com/example/momogum/web/controller/mealPlan/MealPlanController.java
  src/main/java/com/example/momogum/web/dto/mealPlan/MealPlanDTO.java
Labels: :sparkles: feat

#29 [feat] CORS config 구현
  src/main/java/com/example/momogum/config/CorsConfig.java
Labels: :sparkles: feat

#37 [feat] S3 주입 및 밥일기 이미지 CRUD 구현
  build.gradle
  src/main/java/com/example/momogum/apiPayLoad/code/status/ErrorStatus.java
  src/main/java/com/example/momogum/apiPayLoad/exception/handler/ImageHandler.java
  src/main/java/com/example/momogum/apiPayLoad/exception/handler/MealDiaryHandler.java
  src/main/java/com/example/momogum/config/S3Config.java
  src/main/java/com/example/momogum/domain/MealDiary.java
  src/main/java/com/example/momogum/domain/MealDiaryImage.java
  src/main/java/com/example/momogum/domain/common/enums/KeyWord.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryImageRepository.java
  src/main/java/com/example/momogum/service/MealDiaryImageService.java
  src/main/java/com/example/momogum/service/MealDiaryImageServiceImpl.java
  src/main/java/com/example/momogum/service/TestService.java
  src/main/java/com/example/momogum/web/controller/MealDiaryController.java
  src/main/java/com/example/momogum/web/controller/MealDiaryImageController.java
  src/main/java/com/example/momogum/web/controller/TestController.java
  src/main/resources/application.yml
Labels: :sparkles: feat

#39 [fix] PathVarible 변수명 수정
  src/main/java/com/example/momogum/web/controller/MealDiaryImageController.java
Labels: :wrench: fix

#40 [Feat/#31] 약속 잡기 카드 서비스, 컨트롤러 로직 구현
  build.gradle
  src/main/java/com/example/momogum/domain/common/appointment/AppointmentCard.java
  src/main/java/com/example/momogum/domain/common/appointment/AppointmentInvitation.java
  src/main/java/com/example/momogum/domain/common/appointment/AppointmentManager.java
  src/main/java/com/example/momogum/domain/common/enums/Proposal.java
  src/main/java/com/example/momogum/domain/utils/S3UrlProvider.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentCardRepository.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentInvitationRepository.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentManagerRepository.java
  src/main/java/com/example/momogum/service/appointment/AppointmentCardService.java
  src/main/java/com/example/momogum/web/controller/appointment/AppoinmentController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentCardsController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointMentDTO.java
  src/main/resources/application.yml
  src/test/java/com/example/momogum/service/appointment/AppointmentCardServiceTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentCardsControllerTest.java
Labels: :sparkles: feat

#49 [feat] 메인 페이지 조회 리뷰 로직
  src/main/java/com/example/momogum/config/RedisConfig.java
  src/main/java/com/example/momogum/converter/ViewMealDiaryConverter.java
  src/main/java/com/example/momogum/repository/mealDiaryRepo/MealDiaryRepository.java
  src/main/java/com/example/momogum/repository/redisRepository/RedisRepository.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryService.java
  src/main/java/com/example/momogum/service/viewMealDiaryService/ViewMealDiaryServiceImpl.java
  src/main/java/com/example/momogum/web/controller/viewMealDiary/ViewMealDiaryController.java
  src/main/java/com/example/momogum/web/dto/viewMealDiary/ViewMealDiaryDTO.java
Labels: :sparkles: feat

#51 [feat/#41] 약속 식사 모임 이름 정하기 구현
  .gitignore
  build.gradle
  src/main/java/com/example/momogum/converter/Converter.java
  src/main/java/com/example/momogum/converter/appointment/AppointmentNameConverter.java
  src/main/java/com/example/momogum/domain/UserEntity.java
  src/main/java/com/example/momogum/domain/appointment/AppointmentCard.java
  src/main/java/com/example/momogum/domain/appointment/AppointmentInvitation.java
  src/main/java/com/example/momogum/domain/appointment/AppointmentName.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentCardRepository.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentInvitationRepository.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentManagerRepository.java
  src/main/java/com/example/momogum/repository/appoinmentRepo/AppointmentNameRepository.java
  src/main/java/com/example/momogum/service/appointment/AppointmentNameService.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentCardsController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentController.java
  src/main/java/com/example/momogum/web/controller/appointment/AppointmentNameController.java
  src/main/java/com/example/momogum/web/dto/appointment/AppointMentDTO.java
  src/test/java/com/example/momogum/service/appointment/AppointmentNameServiceTest.java
  src/test/java/com/example/momogum/web/controller/appointment/AppointmentNameControllerTest.java
Labels: :sparkles: feat
